#!/usr/bin/env bash

set -euo pipefail

echo "¡Por el poder de Torvalds!"
sleep 1
echo "¡Arch... Yo te actualizo!"
sleep 1

echo -e "\n\033[1;36mActualizando sistema...\033[0m"
if sudo pacman -Syu; then
    echo -e "\n\033[1;32m¡Actualización completa con éxito! :v\033[0m"
    
else
    echo -e "\n\033[1;31mAlgo falló... ¿Será que Windows hizo de las suyas? >:v\033[0m"
    exit 1
fi
