#!/bin/bash

case "$1" in
f)
  feh --randomize --bg-fill ~/.config/i3/fondos/* 
  ;;

t)
  picom &
  ;;

a)
  feh --randomize --bg-fill ~/.config/i3/fondos/* && picom &
  ;;

k)
  killall picom
  ;;

*)
  echo "Uso [ f | t | a | k ]"
  ;;
esac
