#!/bin/bash

echo "¡Por el poder de Torvalds!"
sleep 1
echo "¡Arch... Yo te actualizo!"
sudo pacman -Syu

if [ $? -eq 0 ]; then

  echo "¡Actualización completa con exito!:v"
else
  echo "Algo fallo... ¿Será que Windows hizo de las suyas? >:v"
fi
